//FETCH USER ORGS
export const GET_ORG_START = 'GET_ORG_START';
export const GET_ORG_SUCCESS = 'GET_ORG_SUCCESS';
export const GET_ORG_ERROR = 'GET_ORG_ERROR';
export const GET_ORG_RESET = 'GET_ORG_RESET';

export const SAVE_TOKEN_AND_ORGID = 'SAVE_TOKEN_AND_ORGID';
export const SIGN_OUT = 'SIGN_OUT';

//FETCH CHANNELS BY ORG ID 

export const FETCH_CHANNELS_START = 'FETCH_CHANNELS_START'
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS'
export const FETCH_CHANNELS_ERROR = 'FETCH_CHANNELS_ERROR'

// FETCH USER DETAILS BY ACCESS TOKEN
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS'

// UPDATE CURRENT ORG ID AFTER ORG SWITCH
export const UPDATE_CURRENT_ORG_ID = 'UPDATE_CURRENT_ORG_ID'

// GET ALL USERS OF A PARTICULAR ORG 
export const GET_ALL_USERS_SUCCESS='GET_ALL_USERS_SUCCESS'