//FETCH USER ORGS
export const GET_ORG_START = 'GET_ORG_START';
export const GET_ORG_SUCCESS = 'GET_ORG_SUCCESS';
export const GET_ORG_ERROR = 'GET_ORG_ERROR';
export const GET_ORG_RESET = 'GET_ORG_RESET';

export const SAVE_TOKEN_AND_ORGID = 'SAVE_TOKEN_AND_ORGID';
export const SIGN_OUT = 'SIGN_OUT';


//SET ACTIVE CHANNEL ID
export const SET_ACTIVE_CHANNEL_TEAMID = 'SET_ACTIVE_CHANNEL_TEAMID'
export const RESET_ACTIVE_CHANNEL_TEAMID ='RESET_ACTIVE_CHANNEL_TEAMID'
//FETCH CHANNELS BY ORG ID 
export const FETCH_CHANNELS_START = 'FETCH_CHANNELS_START'
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS'
export const FETCH_CHAT_RESET = 'FETCH_CHAT_RESET'
export const FETCH_CHANNELS_BY_QUERY_ERROR = 'FETCH_CHANNELS_BY_QUERY_ERROR'
export const FETCH_CHANNELS_BY_QUERY_START = 'FETCH_CHANNELS_BY_QUERY_START'
export const FETCH_CHANNELS_BY_QUERY_SUCCESS = 'FETCH_CHANNELS_BY_QUERY_SUCCESS'
export const FETCH_CHANNELS_ERROR = 'FETCH_CHANNELS_ERROR'
export const MOVE_CHANNEL_TO_TOP = 'MOVE_CHANNEL_TO_TOP'

//CREATE CHANNELS
export const CREATE_NEW_CHANNEL_START = 'CREATE_NEW_CHANNEL_START'
export const CREATE_NEW_CHANNEL_SUCCESS = 'CREATE_NEW_CHANNEL_SUCCESS'
export const CREATE_NEW_DM_CHANNEL_START = 'CREATE_NEW_DM_CHANNEL_START'

//NEW USER JOINED A ORG
export const NEW_USER_JOINED_ORG = 'NEW_USER_JOINED_ORG'


//CHAT
export const FETCH_CHAT_START = 'FETCH_CHAT_START';
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const FETCH_CHAT_ERROR = 'FETCH_CHAT_ERROR';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';

//DELETE MESSAGE
export const DELETE_MESSAGE_START ='DELETE_MESSAGE_START'
export const DELETE_MESSAGE_SUCCESS ='DELETE_MESSAGE_SUCCESS'

export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';

// FETCH USER DETAILS BY ACCESS TOKEN
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS'

// UPDATE CURRENT ORG ID AFTER ORG SWITCH
export const UPDATE_CURRENT_ORG_ID = 'UPDATE_CURRENT_ORG_ID'

// GET ALL USERS OF A PARTICULAR ORG 
export const GET_ALL_USERS_SUCCESS='GET_ALL_USERS_SUCCESS'

//SUBSCRIBE TO NOTIFICATIONS

export const SUBSCRIBE_TO_NOTIFICATIONS= 'SUBSCRIBE_TO_NOTIFICATIONS'