//FETCH USER ORGS
export const GET_ORG_START = 'GET_ORG_START';
export const GET_ORG_SUCCESS = 'GET_ORG_SUCCESS';
export const GET_ORG_ERROR = 'GET_ORG_ERROR';
export const GET_ORG_RESET = 'GET_ORG_RESET';

